# Generated by Django 4.2.6 on 2023-10-18 14:45

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ToDoItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField(verbose_name="description")),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "modified",
                    models.DateTimeField(auto_now=True, verbose_name="modified"),
                ),
                (
                    "completed",
                    models.BooleanField(default=False, verbose_name="published"),
                ),
            ],
            options={
                "verbose_name": "item",
                "verbose_name_plural": "items",
                "ordering": ["created"],
            },
        ),
    ]
