# Generated by Django 4.2.6 on 2023-10-18 16:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todolist", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="todoitem",
            options={"ordering": ["created"]},
        ),
        migrations.AddField(
            model_name="todoitem",
            name="priority",
            field=models.BooleanField(default=False, verbose_name="priority"),
        ),
        migrations.AlterField(
            model_name="todoitem",
            name="completed",
            field=models.BooleanField(default=False, verbose_name="completed"),
        ),
        migrations.AlterField(
            model_name="todoitem",
            name="description",
            field=models.TextField(max_length=200, verbose_name="description"),
        ),
    ]
