# This workflow will install Python dependencies and run unit tests

name: Run unit tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11.5
      uses: actions/setup-python@v3
      with:
        python-version: "3.11.5"
    - name: Install and configure Poetry
      uses: snok/install-poetry@v1
    - name: Install dependencies
      run: |
        poetry install
    - name: Run unit tests
      run: |
        poetry shell && python reminders/manage.py test
